### ISSUE TITLE
[BUG] Zotero references functionality not working (1.7.10)

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#906]
## Description

The reference functionality seems completely disabled. `[@]` does not call the drop down menu, and existing references don't actually do anything.

## Reproducing

Try using the functionality.

## Platform
 - OS and version: OS X 10.14.4
 - Zettlr Version: 1.7.10 Beta

## Additional information

Worked in 1.7.9

Got the following error messages, although I suppose they are not necessarily tied to the issue. Last one might be a clue:

* `GET file:///Applications/Zettlr.app/Contents/Resources/app.asar/renderer/assets/vue/sidebar.css net::ERR_FILE_NOT_FOUND`

* `/Applications/Zettlr.app/Contents/Resources/app.asar/renderer/util/load-icons.js:23 Uncaught (in promise) TypeError: x.isDirectory is not a function
    at /Applications/Zettlr.app/Contents/Resources/app.asar/renderer/util/load-icons.js:23
    at Array.map (<anonymous>)
    at /Applications/Zettlr.app/Contents/Resources/app.asar/renderer/util/load-icons.js:22`

*  `/Applications/Zettlr.app/Contents/Resources/app.asar/renderer/zettlr-attachments.js:90 Uncaught TypeError: Cannot read property 'replace' of undefined
    at ZettlrAttachments.refresh (/Applications/Zettlr.app/Contents/Resources/app.asar/renderer/zettlr-attachments.js:90)
    at ZettlrRenderer.setCurrentDir (/Applications/Zettlr.app/Contents/Resources/app.asar/renderer/zettlr-renderer.js:647)
    at ZettlrRendererIPC.handleEvent (/Applications/Zettlr.app/Contents/Resources/app.asar/renderer/zettlr-rendereripc.js:303)
    at ZettlrRendererIPC.dispatch (/Applications/Zettlr.app/Contents/Resources/app.asar/renderer/zettlr-rendereripc.js:202)
    at EventEmitter.<anonymous> (/Applications/Zettlr.app/Contents/Resources/app.asar/renderer/zettlr-rendereripc.js:72)
    at EventEmitter.emit (events.js:223)
    at Object.onMessage (init.ts:50)`

**Comment by danieltomasz** [comment]
In my 1.7beta10 references appear -  @PhilHem  check if you still haves JSON file at your path

**Comment by PhilHem** [comment]
Yes, it is still there, and works in 1.7.9.

**Comment by PhilHem** [comment]
@danieltomasz , do you also use OS X?

**Comment by danieltomasz** [comment]
Yes, I am on Mac - when I updated from beta8 to beta9 my  path to json file disappear, so   I needed to re-add it 
Im on OS X 10.15.5 but I  know don't if this matter

**Comment by danieltomasz** [comment]
1. Try to re-add the path with file again
2. Check if after adding a new item to  referenced Zotero library you will  see popup info about updating JSON library in Zettlr

**Comment by PhilHem** [comment]
Deleting and then readding did not the trick, however applying a change to the JSON made a difference! It's back working now.  Thanks!

**Comment by PhilHem** [comment]
Huh, it changed to not working again. A restart made it work again, for now, but it seems unstable.

**Comment by nathanlesage** [comment]
> when I updated from beta8 to beta9 my path to json file disappear, so I needed to re-add it

What, why did it disappear o_o This should not have happened! Why didn't you say something? :D 

Alright, for me it's working. BUT.

The error messages you cited mean that somehow apparently the sidebar was not found or something? And this is something that disturbs me much more … wait, let me check the build logs ...

**Comment by nathanlesage** [comment]
Okay, according to the build logs everything is okay, so nevermind. But I have no idea why it's unstable, or why the library file suddenly would disappear from the dialog…

**Comment by danieltomasz** [comment]
References still not showing in the lastest 12 beta in the sidebar

**Comment by nathanlesage** [comment]
What

Erm, now I think I need some more information on what you're actually doing, because this is a case of "works on my machine™" — Are there any errors, etc.?

**Comment by danieltomasz** [comment]
![image](https://user-images.githubusercontent.com/7980381/85066225-d1c50f80-b1ae-11ea-8e03-8402b19b1a57.png)

And the full log when I am adding new reference on the  random file
* the reference in the editor is displayed as reference 
* but there is any clue of it in the sidebar

```
[22:04:50]	>>> IPC IN: file-modified
[22:04:50]	Trying to run command through Application: file-modified
[22:04:50]	No command registered with the application for command file-modified
[22:04:51]	>>> IPC IN: file-modified
[22:04:51]	Trying to run command through Application: file-modified
[22:04:51]	No command registered with the application for command file-modified
[22:04:51]	>>> IPC IN: file-modified
[22:04:51]	Trying to run command through Application: file-modified
[22:04:51]	No command registered with the application for command file-modified
[22:04:52]	>>> IPC IN: file-modified
[22:04:52]	Trying to run command through Application: file-modified
[22:04:52]	No command registered with the application for command file-modified
[22:04:56]	>>> IPC IN: file-modified
[22:04:56]	Trying to run command through Application: file-modified
[22:04:56]	No command registered with the application for command file-modified
[22:04:56]	>>> IPC IN: file-modified
[22:04:56]	Trying to run command through Application: file-modified
[22:04:56]	No command registered with the application for command file-modified
[22:05:01]	>>> IPC IN: file-save
[22:05:01]	Trying to run command through Application: file-save
[22:05:01]	<<< IPC OUT: tags-database
[22:05:01]	<<< IPC OUT: tags-database
[22:05:01]	<<< IPC OUT: mark-clean
[22:05:01]	<<< IPC OUT: file-replace
[22:05:01]	[WATCHDOG] Ignore event: change:/Users/daniel/Dropbox/zk_notes/!! ⚡PHD/Programowanie/Pop Shell - shotcuts for window management.md
```

**Comment by nathanlesage** [comment]
Ah, is that a standalone reference without square brackets (e.g. `@citekey` instead of `[@citekey]`)?

If so: I need to add that behaviour later on, I haven't come to that

**Comment by danieltomasz** [comment]
Yes, citation with brackets is appearing in the references!!

Sorry for not checking [] but I was confused, because in 1.6 the citation without [] worked.

**Comment by nathanlesage** [comment]
> because in 1.6 the citation without [] worked.

Yes, it's something I forgot to add in https://github.com/Zettlr/Citr, I need to implement that there in the future, but not now, because I finally want 1.7 happening :D 

If I forget this, please feel free to open up an issue there!
